"""TEST-ONLY: write a fake PTB-XL 1.0.3 tree and fake NSTDB noise records.

The files follow the real PhysioNet layouts so the real loaders run unchanged:
  <out>/ptb-xl/ptbxl_database.csv, scp_statements.csv,
  <out>/ptb-xl/records500/XX000/XXXXX_hr.{dat,hea}   (12 leads, 500 Hz, 10 s, fmt 16, 1000 adu/mV)
  <out>/ptb-xl/records100/XX000/XXXXX_lr.{dat,hea}   (same signal decimated to 100 Hz)
  <out>/nstdb/{bw,ma,em}.{dat,hea}                   (2 channels noise1/noise2, 360 Hz, fmt 212)
The signals are NOT physiological; they only exercise the pipeline.

    python tests/make_synthetic_data.py --out <dir> --n-records 200
"""
from __future__ import annotations

import argparse
import os

import numpy as np
import pandas as pd
import wfdb
from scipy.signal import resample_poly

FS, N_SAMPLES = 500, 5000
NSTDB_FS = 360
LEADS = ["I", "II", "III", "AVR", "AVL", "AVF", "V1", "V2", "V3", "V4", "V5", "V6"]  # as in PTB-XL headers
DB_COLUMNS = ["ecg_id", "patient_id", "age", "sex", "height", "weight", "nurse", "site", "device",
              "recording_date", "report", "scp_codes", "heart_axis", "infarction_stadium1",
              "infarction_stadium2", "validated_by", "second_opinion", "initial_autogenerated_report",
              "validated_by_human", "baseline_drift", "static_noise", "burst_noise",
              "electrodes_problems", "extra_beats", "pacemaker", "strat_fold", "filename_lr",
              "filename_hr"]

# Verbatim rows of the real scp_statements.csv (PTB-XL 1.0.3) for the codes used below.
SCP_STATEMENTS_CSV = """\
,description,diagnostic,form,rhythm,diagnostic_class,diagnostic_subclass,Statement Category,SCP-ECG Statement Description,AHA code,aECG REFID,CDISC Code,DICOM Code
NDT,non-diagnostic T abnormalities,1.0,1.0,,STTC,STTC,other ST-T descriptive statements,non-diagnostic T abnormalities,,,,
NORM,normal ECG,1.0,,,NORM,NORM,Normal/abnormal,normal ECG,1,,,F-000B7
IMI,inferior myocardial infarction,1.0,,,MI,IMI,Myocardial Infarction,inferior myocardial infarction,161,,,
LVH,left ventricular hypertrophy,1.0,,,HYP,LVH,Ventricular Hypertrophy,left ventricular hypertrophy,142,,C71076,
ISC_,non-specific ischemic,1.0,,,STTC,ISC_,Basic roots for coding ST-T changes and abnormalities,ischemic ST-T changes,226,,,
IRBBB,incomplete right bundle branch block,1.0,,,CD,IRBBB,Intraventricular and intra-atrial Conduction disturbances,incomplete right bundle branch block,105,MDC_ECG_BEAT_RBB_BLK_INCOMP,C71048,D3-33112
CLBBB,complete left bundle branch block,1.0,,,CD,CLBBB,Intraventricular and intra-atrial Conduction disturbances,(complete) left bundle branch block,104,MDC_ECG_BEAT_LBB_BLK_COMP,C62269,D3-33120 or 122752
AMI,anterior myocardial infarction,1.0,,,MI,AMI,Myocardial Infarction,anterior myocardial infarction,160,,,
RVH,right ventricular hypertrophy,1.0,,,HYP,RVH,Ventricular Hypertrophy,right ventricular hypertrophy,143,,C71077,
LVOLT,low QRS voltages in the frontal and horizontal leads,,1.0,,,,Other QRS morphology descriptive statements,low QRS voltages in the frontal and horizontal leads,,,,
SR,sinus rhythm,,,1.0,,,Statements related to impulse formation (abnormalities),sinus rhythm,20,MDC_ECG_RHY_SINUS_RHY,,
STACH,sinus tachycardia,,,1.0,,,Statements related to impulse formation (abnormalities),sinus tachycardia,21,MDC_ECG_RHY_SINUS_TACHY,,
"""

# scp_codes patterns cycled over records: every superclass, multi-label records,
# zero-likelihood diagnostic codes (still counted) and records with no superclass.
SCP_PATTERNS = [
    {"NORM": 100.0, "SR": 0.0},
    {"IMI": 100.0, "SR": 0.0},
    {"NDT": 50.0, "STACH": 0.0},
    {"CLBBB": 100.0},
    {"LVH": 80.0, "LVOLT": 0.0, "SR": 0.0},
    {"AMI": 80.0, "ISC_": 50.0, "SR": 0.0},          # MI + STTC
    {"IRBBB": 100.0, "RVH": 0.0, "NDT": 0.0},        # CD + HYP + STTC (zero likelihoods)
    {"SR": 0.0},                                      # no superclass -> dropped
    {"LVOLT": 0.0, "STACH": 0.0},                     # no superclass -> dropped
]

# (P, Q, R, S, T): offset from R peak [s], width [s], amplitude [mV]
_WAVES = [(-0.20, 0.025, 0.15), (-0.03, 0.010, -0.10), (0.0, 0.012, 1.0),
          (0.03, 0.010, -0.25), (0.28, 0.045, 0.30)]


def synth_ecg(rng: np.random.Generator, n: int = N_SAMPLES, fs: int = FS) -> np.ndarray:
    """One lead of a crude ECG: Gaussian-bump PQRST train + baseline drift + noise (mV)."""
    t = np.arange(n) / fs
    rr = 60.0 / rng.uniform(50, 100)
    beats = np.arange(rng.uniform(0.2, rr), n / fs + 0.5, rr) + rng.normal(0, 0.01, 1)
    x = np.zeros(n)
    for c, w, a in _WAVES:
        centers = beats + c
        x += a * np.exp(-0.5 * ((t[:, None] - centers[None]) / w) ** 2).sum(1)
    x *= rng.uniform(0.5, 1.5)
    x += 0.1 * np.sin(2 * np.pi * rng.uniform(0.1, 0.3) * t + rng.uniform(0, 2 * np.pi))
    x += rng.uniform(-0.2, 0.2) + 0.01 * rng.standard_normal(n)
    return x


def make_ptbxl(out: str, n_records: int, rng: np.random.Generator) -> pd.DataFrame:
    root = os.path.join(out, "ptb-xl")
    os.makedirs(root, exist_ok=True)
    with open(os.path.join(root, "scp_statements.csv"), "w") as f:
        f.write(SCP_STATEMENTS_CSV)

    rows = []
    for i in range(n_records):
        ecg_id = i + 1
        patient = i // 2                                  # 2 records per patient
        sub = f"{(ecg_id // 1000) * 1000:05d}"
        noise_flag = ", I-V1, " if i % 7 == 0 else np.nan
        rows.append({
            "ecg_id": ecg_id, "patient_id": float(10000 + patient), "age": float(rng.integers(20, 90)),
            "sex": int(rng.integers(2)), "nurse": 2.0, "site": 0.0, "device": "CS-12   E",
            "recording_date": "1990-01-01 00:00:00", "report": "synthetic",
            "scp_codes": str(SCP_PATTERNS[i % len(SCP_PATTERNS)]),
            "second_opinion": False, "initial_autogenerated_report": False, "validated_by_human": True,
            "baseline_drift": noise_flag, "static_noise": np.nan, "burst_noise": np.nan,
            "electrodes_problems": np.nan,
            "strat_fold": patient % 10 + 1,               # patient-level folds
            "filename_lr": f"records100/{sub}/{ecg_id:05d}_lr",
            "filename_hr": f"records500/{sub}/{ecg_id:05d}_hr",
        })
        sig = np.stack([synth_ecg(rng) * s for s in rng.uniform(0.3, 1.2, len(LEADS))], axis=1)
        for folder, suffix, fs, x in (("records500", "hr", FS, sig),
                                      ("records100", "lr", 100, resample_poly(sig, 1, 5, axis=0))):
            rec_dir = os.path.join(root, folder, sub)
            os.makedirs(rec_dir, exist_ok=True)
            wfdb.wrsamp(f"{ecg_id:05d}_{suffix}", fs=fs, units=["mV"] * len(LEADS), sig_name=LEADS,
                        p_signal=x, fmt=["16"] * len(LEADS), adc_gain=[1000.0] * len(LEADS),
                        baseline=[0] * len(LEADS), write_dir=rec_dir)
    db = pd.DataFrame(rows).reindex(columns=DB_COLUMNS)
    db.to_csv(os.path.join(root, "ptbxl_database.csv"), index=False)
    return db


def make_nstdb(out: str, seconds: float, rng: np.random.Generator) -> None:
    root = os.path.join(out, "nstdb")
    os.makedirs(root, exist_ok=True)
    n = int(seconds * NSTDB_FS)
    t = np.arange(n) / NSTDB_FS
    for name in ("bw", "ma", "em"):
        chans = []
        for _ in range(2):
            if name == "bw":      # slow wander
                x = sum(rng.uniform(0.2, 0.6) * np.sin(2 * np.pi * rng.uniform(0.05, 0.5) * t
                                                       + rng.uniform(0, 2 * np.pi)) for _ in range(3))
            elif name == "ma":    # broadband
                x = 0.1 * rng.standard_normal(n)
            else:                 # random-walk steps + broadband
                x = np.cumsum(0.02 * rng.standard_normal(n)) + 0.05 * rng.standard_normal(n)
                x -= x.mean()
            chans.append(np.clip(x, -9.0, 9.0))
        wfdb.wrsamp(name, fs=NSTDB_FS, units=["mV", "mV"], sig_name=["noise1", "noise2"],
                    p_signal=np.stack(chans, axis=1), fmt=["212", "212"], adc_gain=[200.0, 200.0],
                    baseline=[0, 0], write_dir=root)


def make_synthetic(out: str, n_records: int = 200, seed: int = 0, nstdb_seconds: float = 120.0) -> None:
    rng = np.random.default_rng(seed)
    make_ptbxl(out, n_records, rng)
    make_nstdb(out, nstdb_seconds, rng)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True)
    ap.add_argument("--n-records", type=int, default=200)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--nstdb-seconds", type=float, default=120.0)
    a = ap.parse_args()
    make_synthetic(a.out, a.n_records, a.seed, a.nstdb_seconds)
    print(f"wrote {a.out}/ptb-xl ({a.n_records} records) and {a.out}/nstdb")


if __name__ == "__main__":
    main()
