"""The single descriptive fold-10 reporting pass (RULES2.md section 4). Reads results/track2/grid/report_fold10.
Logs each 3-seed average as a fold-10 entry (once), writes results/track2/fold10_report.{md,json}.
Nothing here is used for selection."""
from __future__ import annotations

import json
import os

import nstdb
from corruptions import MODES, SEEN, UNSEEN, cond_name
from fold10_log import LOG, log_fold10
from t2lib import D, REGIMES, Grid, ci, f4, fmt_boot, mean_std, paired

MODELS = ["B0-clean", "B0-aug", "C", "D", "E", "F"]
g = Grid("report_fold10", {k: REGIMES[k] for k in MODELS})
assert list(g.regimes) == MODELS
for k in MODELS:
    tag = f"track2 grid 'report': 3-seed average {k}"
    if tag not in open(LOG).read():
        log_fold10(tag, g.regimes[k], "RULES2.md section 4: mean of the 3 probabilities above (no selection)")

c = lambda fams, snrs: [cond_name(f, s, m) for f in fams for s in snrs for m in MODES]
G = {"clean": ["clean"]}
for s in [-6.0, 0.0]:
    G.update({f"{n}@{s:+.0f}": c(f, [s]) for n, f in [("seen_families", SEEN), ("unseen_families", UNSEEN),
                                                       ("mixed", ["mixed"]), ("all_corrupted", SEEN + UNSEEN + ["mixed"])]})
G.update({f: c([f], nstdb.SNRS) for f in nstdb.FAMILIES})
G["nstdb_all"] = c(nstdb.FAMILIES, nstdb.SNRS)
G["nstdb_all@-6"] = c(nstdb.FAMILIES, [-6.0])
G["nstdb_mixed@-6"] = c(["nstdb_mixed"], [-6.0])
assert all(x in g.ix for cs in G.values() for x in cs)

ens = {k: {grp: g.score(g.ens[k], cs) for grp, cs in G.items()} for k in MODELS}
seed = {k: {grp: [g.score(P, cs) for P in g.seed[k]] for grp, cs in G.items()} for k in MODELS}
bs = g.boot(g.ens, G)
cis = {grp: {k: ci(bs[grp][k]) for k in MODELS} for grp in G}
pr = {grp: {k: paired(bs[grp], {m: ens[m][grp] for m in MODELS}, k, "B0-aug") for k in MODELS if k != "B0-aug"} for grp in G}
json.dump({"ensemble": ens, "per_seed": seed, "ci": cis, "paired_vs_B0aug": pr}, open(os.path.join(D, "fold10_report.json"), "w"), indent=1)

f9 = {}
for name in ["main", "nstdb"]:
    gg = Grid(name, {k: REGIMES[k] for k in MODELS})
    for k in MODELS:
        for grp, cs in G.items():
            if all(x in gg.ix for x in cs):
                f9.setdefault(k, {})[grp] = gg.score(gg.ens[k], cs)

SECTIONS = [("Clean and synthetic corruptions at -6 dB", ["clean", "seen_families@-6", "unseen_families@-6", "mixed@-6", "all_corrupted@-6"]),
            ("Synthetic corruptions at 0 dB", ["seen_families@+0", "unseen_families@+0", "mixed@+0", "all_corrupted@+0"]),
            ("NSTDB real noise (EVAL noise; per family = 0 and -6 dB pooled)", nstdb.FAMILIES + ["nstdb_all", "nstdb_all@-6", "nstdb_mixed@-6"])]
L = ["# Track 2 fold-10 reporting pass (descriptive, not selection)", "",
     "Rules: RULES2.md section 4 (freeze and this pass were written and committed before scoring). Models frozen; "
     "nothing below was used to choose anything. Every model and 3-seed average is logged in FOLD10_LOG.md "
     "(#13-30 single models, #31-36 averages).",
     "Conditions are generated by the same seeded generators as on fold 9 (keyed by ecg_id). Group = mean macro-AUROC over "
     "its conditions (both modes). CIs: patient bootstrap, 1000 resamples, seed 0; paired differences vs B0-aug use the "
     "same resamples.", ""]
for title, cols in SECTIONS:
    L += [f"## {title}", "", "3-seed probability average, 95% CI:", "", "| model | " + " | ".join(cols) + " |", "|---" * (len(cols) + 1) + "|"]
    for k in MODELS:
        L.append(f"| {k} | " + " | ".join(f"{f4(ens[k][x])} [{cis[x][k][0]:.4f}, {cis[x][k][1]:.4f}]" for x in cols) + " |")
    L += ["", "Per seed (0-2):", "", "| model | " + " | ".join(cols) + " |", "|---" * (len(cols) + 1) + "|"]
    for k in MODELS:
        L.append(f"| {k} | " + " | ".join(" / ".join(f4(v) for v in seed[k][x]) + f" ({mean_std(seed[k][x])})" for x in cols) + " |")
    L += ["", "Paired difference vs B0-aug (3-seed averages), [95% CI]:", "", "| model | " + " | ".join(cols) + " |", "|---" * (len(cols) + 1) + "|"]
    for k in MODELS:
        if k != "B0-aug":
            L.append(f"| {k} - B0-aug | " + " | ".join(fmt_boot(pr[x][k]) for x in cols) + " |")
    L += ["", "Fold 9 vs fold 10 (3-seed average):", "", "| model | " + " | ".join(cols) + " |", "|---" * (len(cols) + 1) + "|"]
    for k in MODELS:
        L.append(f"| {k} | " + " | ".join(f"{f4(f9[k][x])} -> {f4(ens[k][x])}" if x in f9[k] else f"n/a -> {f4(ens[k][x])}" for x in cols) + " |")
    L.append("")
open(os.path.join(D, "fold10_report.md"), "w").write("\n".join(L) + "\n")
print("\n".join(L))
